# Coding Temple's Data Analytics Program  
---
# Advanced Python 1 - Intro to `numpy`
---



## Part 1: Working with `numpy`


### 1.1 Importing `numpy`

We've already used the `numpy` package by importing it and assigning it the standard alias of `np`. Do this again in the following cell - the more you practice typing these lines of code, the easier it will be to remember.

In [1]:
# Import numpy and assign it the standard alias
# YOUR CODE HERE
import numpy as np

### 1.1 Solution - Run this cell to check your answer in 1.1. Please do not edit the values in this cell!

In [2]:
# DO NOT EDIT THIS CELL
assert np.__name__ == 'numpy', 'Make sure that you have properly imported numpy and aliased it as np!'

### 1.2 Generate random numbers

Create a `(5,3)` `numpy` array of random integer values between 0 and 100.

Use the the `random()` method in numpy to generate these integers. Name your new variable `myarray`. You should also print the array to check it's dimensions and values.

In [5]:
# Generate your random numbers
np.random.seed(1) #Seed generated for reproducibility #YOUR CODE HERE

myarray = np.random.randint(0,100, (5,3))
print(myarray)
print(f' get the first array out of the matrix: {myarray[0]}')

# Print out the array


[[37 12 72]
 [ 9 75  5]
 [79 64 16]
 [ 1 76 71]
 [ 6 25 50]]
 get the first array out of the matrix: [37 12 72]


### 1.2 Solution - Run the following cell to check your answer.

In [6]:
#DO NOT EDIT THIS CELL

#Verify the array was created with the correct name and has the proper shape
assert myarray.shape == (5,3), 'Make sure you create an array with the proper shape!'

### 1.3 Calculate BMI 

Using the two lists provided, please calculate the BMI(body mass index) of each individual using NDArrays. Save the variable containing your results as `bmi`

The formula for BMI in pounds and inches can be defined as: $BMI= \frac{703 * weight} {(height)^2}$

In [13]:
height = [55, 120, 90, 100]
weight = [170, 180, 190, 200]
#bmi = weight / height

arr1 = np.array(height)
arr2 = np.array(weight)*2

bmi = arr2 / arr1
print(bmi)

[6.18181818 3.         4.22222222 4.        ]


### 1.3 Solution: Run the following cell to check your answer.

In [14]:
# DO NOT EDIT THIS CELL
assert 'bmi' in dir() , 'Make sure you have saved your results to the proper variable name!'
assert type(bmi) == np.ndarray, 'Make sure that you made the calculation using an NDArray for both height and weight!'


### 1.4 Create a function 

Create a function named `my_func` that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [38]:
import numpy as np

np.random.seed(5)

my_func= np.random.randint(0,100, (5,3))
print(my_func)

M = my_func
print(M)




[[99 78 61]
 [16 73  8]
 [62 27 30]
 [80  7 76]
 [15 53 80]]
[[99 78 61]
 [16 73  8]
 [62 27 30]
 [80  7 76]
 [15 53 80]]


### 1.5 Array practice

Time for some more practice. Run each of these tasks in the separate code cell listed below:

1.  Return the first row
2.  Return the last column
3.  Return the third column values from the 4th and 5th rows
4.  Multiply every value in the array by 2
5.  Divide every value by 3
6.  Increase the values in the first row by 12
7. Calculate the mean of the first column
8. Calculate the median of the array _after_ removing the 2 smallest values in the array
9. Calculate the standard deviation of the first 3 rows
10. Return values greater than 25 in the second column
11. Return values less than 40 in the array

In [39]:
# 1. Return the first row:
print(M[0])

[99 78 61]


In [41]:
# 2. Return the last column
print(M[:,-1])


[61  8 30 76 80]


In [46]:
# 3. Return the third column values from the 4th and 5th rows
print(M[3:5,2])

[76 80]


In [47]:
# 4. Multiply every value in the array by 2
M*2
print(M*2)

[[198 156 122]
 [ 32 146  16]
 [124  54  60]
 [160  14 152]
 [ 30 106 160]]


In [48]:
# 5. Divide every value by 3
print(M/3)

[[33.         26.         20.33333333]
 [ 5.33333333 24.33333333  2.66666667]
 [20.66666667  9.         10.        ]
 [26.66666667  2.33333333 25.33333333]
 [ 5.         17.66666667 26.66666667]]


In [49]:
# 6. Increase the values in the first row by 12
inc = M + 12
print(inc)

[[111  90  73]
 [ 28  85  20]
 [ 74  39  42]
 [ 92  19  88]
 [ 27  65  92]]


In [52]:
# 7. Calculate the mean of the first column
print(int(np.mean(M[:,0])))


54


In [55]:
# 8. Calculate the median of the array after removing the 2 smallest values in the array
print(M[:,0])

print(f'\n HIghest values: (M>[50])'

SyntaxError: incomplete input (196590911.py, line 4)

In [ ]:
# 9. Calculate the standard deviation of the first 3 rows
# Generate a new array to work on
np.random.seed(2) # New seed for new array


In [58]:
# 10. Return values in the second column greater than 25
print(M[:, 2] >25)

[ True False  True  True  True]


In [63]:
# 11. Return values < 40 in the array
print(M[:, :] <40)



[[False False False]
 [ True False  True]
 [False  True  True]
 [False  True False]
 [ True False False]]


### Solution 1.5: Run the following cell to view the solution for each of the above tasks.

A new array will be generated to demonstrate the solution - the values will not be the same as your array. But the code for each task will still apply.

In [ ]:
# DO NOT EDIT THIS CELL
# SOLUTION 1.5

# SOLUTION: Make sure you have completed all of the above tasks
# Generate your random numbers (NEW ARRAY)
myarray = np.random.randint(100, size=(5, 3))
print('The generated array: \n', myarray)
print('\n')

# 1. Return the first row:
print('1. The first row: ', myarray[0])
print('\n')

# 2. Return the last column
print('2. The last column: ', myarray[:,-1])
print('\n')

# 3. Return the third column values from the 4th and 5th rows
print('3. The 3rd column, 4th & 5th rows: ', myarray[3:5,2])
print('\n')

# 4. Multiply every value in the array by 2
# (operates on the original array)
print('4. Multiply by 2: \n', myarray * 2)
print('\n')

# 5. Divide every value by 3
# (operates on the original array)
print('5. Divide by 3: \n', myarray / 3)
print('\n')

# 6. Increase the values in the first row by 12
# (operates on the original array)
print('6. Add 12 to the first row: \n', myarray[0,:] + 12)
print('\n')

# 7. Calculate the mean of the first column
print('7. The mean of the 1st column: ', myarray[:,0].mean())
print('\n')

# 8. Calculate the median of the array after removing the 2 smallest values in the array
# flatten and sort (axis=None does the flattening)
myarray = np.sort(myarray, axis=None)
# remove two smallest values
myarray = myarray[2:]
# calculate the median
print('8. The median after removing the 2 smallest values: ', np.median(myarray))
print('\n')

# 9. Calculate the standard deviation of the first 3 rows
# Generate new array first:
myarray = np.random.randint(100, size=(5, 3))
# Then calculate the std:
print('9. The standard deviation is: ', np.std(myarray[0:3,:]))
print('\n')

# 10. Return values in the second column greater than 25
# create a Boolean mask where values in the 2nd column > 25 are True
condition = myarray[:,1] > 25
# Apply the mask
print('10. All values in 2nd column > 25: \n', myarray[condition])
print('\n')

# 11. Return values < 40 in the array
# create another Boolean mask for values < 40
condition = myarray < 40
# apply the mask
print('11. All values < 40: \n', myarray[condition])